### ISSUE TITLE
Additions/fixes for flags

### ISSUE THREAD

**Issue by anaknaga** [kdave/linux-pax-flags#1]
After installing and playing with grsec on openSUSE 42.2 Gnome, I found some errors in the flags, as well as some additions which might prove useful. I will just list the more common use cases here. I'll update if I find more. Also, some of the MPROTECT ones might require more attributes, but I decided to start conservatively, and so far they are working with only this one.

PSmXEr:
        - /home/user/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/firefox #exists in browsers.conf but path  doesn't work. Not sure how to wildcard the 'user' home dir. Downloaded through official tor-browser launcher.

PSmXER:
        - /usr/lib64/thunderbird/thunderbird-bin #wrong path in simple.conf
        - /usr/bin/python3.4
        - /usr/lib/tracker-store #for tracker in gnome
        - /etc/X11/xdm/keytable #prevents some grsec resource denied error before loading dm
        - /usr/bin/grep #prevents some grsec resource denied error before loading dm
        - /usr/bin/gjs-console #for dropdown terminal extension on gnome
        - /usr/bin/rhythmbox
        - /usr/lib/libwebkit2gtk-4_0-37/WebKitWebProcess #epiphany (gnome browser) requirement

**Comment by kdave** [comment]
Thanks! Home directories are referenced `~`. Git updated, I have a few unclear entries:
- /etc/X11/xdm/keytable
- /usr/bin/grep
I need to look at the errors and if it's really necessary to allow the exceptions here.

**Comment by kdave** [comment]
Package `linux-pax-flags` updated.

**Comment by anaknaga** [comment]
Cheers!

These are the errors I found with regards to keytable and grep. I'm not sure what they mean or if they are important. I've removed the xattr on both files for now, as functionality seems to be the same. The keytable one was the parent, so it shouldn't have them set anyway I guess.

Jan 16 21:25:12 T450s-Leap kernel: grsec: denied resource overstep by requesting 64 for RLIMIT_CORE against limit 0 for /usr/bin/grep[grep:1685] uid/euid:0/0 gid/egid:0/0, parent /etc/X11/xdm/keytable[keytable:1684] uid/euid:0/0 gid/egid:0/0
Jan 16 21:25:12 T450s-Leap kernel: grsec: denied resource overstep by requesting 120 for RLIMIT_CORE against limit 0 for /usr/bin/grep[grep:1685] uid/euid:0/0 gid/egid:0/0, parent /etc/X11/xdm/keytable[keytable:1684] uid/euid:0/0 gid/egid:0/0
Jan 16 21:25:12 T450s-Leap kernel: grsec: denied resource overstep by requesting 176 for RLIMIT_CORE against limit 0 for /usr/bin/grep[grep:1685] uid/euid:0/0 gid/egid:0/0, parent /etc/X11/xdm/keytable[keytable:1684] uid/euid:0/0 gid/egid:0/0
Jan 16 21:25:12 T450s-Leap kernel: grsec: denied resource overstep by requesting 232 for RLIMIT_CORE against limit 0 for /usr/bin/grep[grep:1685] uid/euid:0/0 gid/egid:0/0, parent /etc/X11/xdm/keytable[keytable:1684] uid/euid:0/0 gid/egid:0/0
Jan 16 21:25:12 T450s-Leap kernel: grsec: denied resource overstep by requesting 288 for RLIMIT_CORE against limit 0 for /usr/bin/grep[grep:1685] uid/euid:0/0 gid/egid:0/0, parent /etc/X11/xdm/keytable[keytable:1684] uid/euid:0/0 gid/egid:0/0

**Comment by kdave** [comment]
`RLIMIT_CORE` is not critical and does not require a paxctl exception. This needs some documentation or tools to tell a user what to report, it's in the todo.
